/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Program;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAMA
 */
public class tampil_data extends javax.swing.JInternalFrame {

    /** Creates new form tampil_data */
    public tampil_data() {
        initComponents();
        tampil();
    }
   Connection con = null;
    Statement st = null;
    ResultSet rs = null;
 
    public ArrayList<Tanah> selectAll(){
        ArrayList<Tanah> select = new ArrayList<>();
        Tanah tanah = new Tanah();
        String sql = "SELECT * FROM tanah";
        try {
            con = Koneksi.getConnection();
            st = con.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next()){
               tanah = new Tanah(rs.getInt(1),rs.getString(2),rs.getString(3),rs.getFloat(4),rs.getFloat(5),rs.getFloat(6),rs.getString(7));
               select.add(tanah);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return select;
    }
     public void tampil(){
        ArrayList<Tanah> list = selectAll();
        DefaultTableModel model = (DefaultTableModel)table_data_penjualan.getModel();
        Object[] row = new Object[7];
        for (int i=0;i<list.size();i++){
            row[0]=list.get(i).getId();
            row[1]=list.get(i).getPemilik();
            row[2]=list.get(i).getLokasi();
            row[3]=list.get(i).getPanjang();
            row[4]=list.get(i).getLebar();
            row[5]=list.get(i).getHarga();
            row[6]=list.get(i).getHargatotDum();
            
            model.addRow(row);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_data_penjualan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("DATA PENJUALAN TANAH");

        table_data_penjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PEMILIK", "LOKASI", "PANJANG TANAH", "LEBAR TANAH", "HARGA/m2", "HARGA TOTAL"
            }
        ));
        jScrollPane1.setViewportView(table_data_penjualan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(263, 263, 263))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_data_penjualan;
    // End of variables declaration//GEN-END:variables

}
